<?php

namespace Database\Seeders;

use App\Models\Place;
use Illuminate\Database\Seeder;

class PlaceSecondSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $places = [
            [
                'number'=> 101,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 434,
                'posY' => 731,
            ],
            [
                'number'=> 102,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 382,
                'posY' => 731,
            ],
            [
                'number'=> 103,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 352,
                'posY' => 731,
            ],
            [
                'number'=> 104,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 299,
                'posY' => 731,
            ],
            [
                'number'=> 105,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 270,
                'posY' => 731,
            ],
            [
                'number'=> 106,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 217,
                'posY' => 731,
            ],
            [
                'number'=> 107,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 188,
                'posY' => 731,
            ],
            [
                'number'=> 108,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 135,
                'posY' => 731,
            ],
            [
                'number'=> 109,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 106,
                'posY' => 731,
            ],
            [
                'number'=> 110,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 54,
                'posY' => 731,
            ],
            [
                'number'=> 111,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 579,
                'posY' => 835,
            ],
            [
                'number'=> 112,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 579,
                'posY' => 805,
            ],
            [
                'number'=> 113,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 520,
                'posY' => 835,
            ],
            [
                'number'=> 114,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 520,
                'posY' => 805,
            ],
            [
                'number'=> 115,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 490,
                'posY' => 835,
            ],
            [
                'number'=> 116,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 490,
                'posY' => 805,
            ],
            [
                'number'=> 117,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 433,
                'posY' => 835,
            ],
            [
                'number'=> 118,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 433,
                'posY' => 805,
            ],
            [
                'number'=> 119,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 404,
                'posY' => 835,
            ],
            [
                'number'=> 120,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 404,
                'posY' => 805,
            ],
            [
                'number'=> 121,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 346,
                'posY' => 835,
            ],
            [
                'number'=> 122,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 346,
                'posY' => 805,
            ],
            [
                'number'=> 123,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 317,
                'posY' => 835,
            ],
            [
                'number'=> 124,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 317,
                'posY' => 805,
            ],
            [
                'number'=> 125,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 258,
                'posY' => 835,
            ],
            [
                'number'=> 126,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 258,
                'posY' => 805,
            ],
            [
                'number'=> 127,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 227,
                'posY' => 835,
            ],
            [
                'number'=> 128,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 227,
                'posY' => 805,
            ],
            [
                'number'=> 129,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 170,
                'posY' => 835,
            ],
            [
                'number'=> 130,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 170,
                'posY' => 805,
            ],
            [
                'number'=> 131,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 628,
                'posY' => 915,
            ],
            [
                'number'=> 132,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 628,
                'posY' => 885,
            ],
            [
                'number'=> 133,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 569,
                'posY' => 915,
            ],
            [
                'number'=> 134,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 569,
                'posY' => 885,
            ],
            [
                'number'=> 135,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 534,
                'posY' => 915,
            ],
            [
                'number'=> 136,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 534,
                'posY' => 885,
            ],
            [
                'number'=> 137,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 474,
                'posY' => 915,
            ],
            [
                'number'=> 138,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 474,
                'posY' => 885,
            ],
            [
                'number'=> 139,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 442,
                'posY' => 915,
            ],
            [
                'number'=> 140,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 442,
                'posY' => 885,
            ],
            [
                'number'=> 141,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 382,
                'posY' => 915,
            ],
            [
                'number'=> 142,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 382,
                'posY' => 885,
            ],
            [
                'number'=> 143,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 351,
                'posY' => 915,
            ],
            [
                'number'=> 144,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 351,
                'posY' => 885,
            ],
            [
                'number'=> 145,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 292,
                'posY' => 915,
            ],
            [
                'number'=> 146,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 292,
                'posY' => 885,
            ],
            [
                'number'=> 147,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 259,
                'posY' => 915,
            ],
            [
                'number'=> 148,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 259,
                'posY' => 885,
            ],
            [
                'number'=> 149,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 199,
                'posY' => 915,
            ],
            [
                'number'=> 150,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 199,
                'posY' => 885,
            ],
            [
                'number'=> 151,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 167,
                'posY' => 915,
            ],
            [
                'number'=> 152,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 167,
                'posY' => 885,
            ],
            [
                'number'=> 153,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 108,
                'posY' => 915,
            ],
            [
                'number'=> 154,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 108,
                'posY' => 885,
            ],
            [
                'number'=> 155,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 76,
                'posY' => 915,
            ],
            [
                'number'=> 156,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 76,
                'posY' => 885,
            ],
            [
                'number'=> 157,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 17,
                'posY' => 915,
            ],
            [
                'number'=> 158,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 17,
                'posY' => 885,
            ],
            [
                'number'=> 159,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 69,
                'posY' => 839,
            ],
            [
                'number'=> 160,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 13,
                'posY' => 839,
            ],

        ];
        foreach ($places as $place) {
            $place['price'] = 450;
            $place = Place::create($place);
        }
    }
}
