<?php

namespace Database\Seeders;

use App\Models\Place;
use Illuminate\Database\Seeder;

class PlaceSecondSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $places = [
            [
                'number'=> 50,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 421,
                'posY' => 717,
            ],
            [
                'number'=> 51,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 366,
                'posY' => 717,
            ],
            [
                'number'=> 52,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 340,
                'posY' => 717,
            ],
            [
                'number'=> 53,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 288,
                'posY' => 717,
            ],
            [
                'number'=> 54,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 260,
                'posY' => 717,
            ],
            [
                'number'=> 55,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 207,
                'posY' => 717,
            ],
            [
                'number'=> 56,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 181,
                'posY' => 717,
            ],
            [
                'number'=> 57,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 127,
                'posY' => 717,
            ],
            [
                'number'=> 58,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 100,
                'posY' => 717,
            ],
            [
                'number'=> 59,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 44,
                'posY' => 717,
            ],
            [
                'number'=> 60,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 612,
                'posY' => 817,
            ],
            [
                'number'=> 61,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 612,
                'posY' => 791,
            ],
            [
                'number'=> 62,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 555,
                'posY' => 817,
            ],
            [
                'number'=> 63,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 555,
                'posY' => 791,
            ],
            [
                'number'=> 64,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 476,
                'posY' => 817,
            ],
            [
                'number'=> 65,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 476,
                'posY' => 791,
            ],
            [
                'number'=> 66,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 419,
                'posY' => 817,
            ],
            [
                'number'=> 67,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 419,
                'posY' => 791,
            ],
            [
                'number'=> 68,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 390,
                'posY' => 817,
            ],
            [
                'number'=> 69,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 390,
                'posY' => 791,
            ],
            [
                'number'=> 70,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 334,
                'posY' => 817,
            ],
            [
                'number'=> 71,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 334,
                'posY' => 791,
            ],
            [
                'number'=> 72,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 305,
                'posY' => 817,
            ],
            [
                'number'=> 73,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 305,
                'posY' => 791,
            ],
            [
                'number'=> 74,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 248,
                'posY' => 817,
            ],
            [
                'number'=> 75,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 248,
                'posY' => 791,
            ],
            [
                'number'=> 76,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 218,
                'posY' => 817,
            ],
            [
                'number'=> 77,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 218,
                'posY' => 791,
            ],
            [
                'number'=> 78,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 161,
                'posY' => 817,
            ],
            [
                'number'=> 79,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 161,
                'posY' => 791,
            ],
            [
                'number'=> 80,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 612,
                'posY' => 898,
            ],
            [
                'number'=> 81,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 612,
                'posY' => 870,
            ],
            [
                'number'=> 82,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 551,
                'posY' => 898,
            ],
            [
                'number'=> 83,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 551,
                'posY' => 870,
            ],
            [
                'number'=> 84,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 521,
                'posY' => 898,
            ],
            [
                'number'=> 85,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 521,
                'posY' => 870,
            ],
            [
                'number'=> 86,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 459,
                'posY' => 898,
            ],
            [
                'number'=> 87,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 459,
                'posY' => 870,
            ],
            [
                'number'=> 88,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 430,
                'posY' => 898,
            ],
            [
                'number'=> 89,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 430,
                'posY' => 870,
            ],
            [
                'number'=> 90,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 368,
                'posY' => 898,
            ],
            [
                'number'=> 91,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 368,
                'posY' => 870,
            ],
            [
                'number'=> 92,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 341,
                'posY' => 898,
            ],
            [
                'number'=> 93,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 341,
                'posY' => 870,
            ],
            [
                'number'=> 94,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 281,
                'posY' => 898,
            ],
            [
                'number'=> 95,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 281,
                'posY' => 870,
            ],
            [
                'number'=> 96,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 252,
                'posY' => 898,
            ],
            [
                'number'=> 97,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 252,
                'posY' => 870,
            ],
            [
                'number'=> 98,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 191,
                'posY' => 898,
            ],
            [
                'number'=> 99,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 191,
                'posY' => 870,
            ],
            [
                'number'=> 100,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 162,
                'posY' => 898,
            ],
            [
                'number'=> 101,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 162,
                'posY' => 870,
            ],
            [
                'number'=> 102,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 101,
                'posY' => 898,
            ],
            [
                'number'=> 103,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 101,
                'posY' => 870,
            ],
            [
                'number'=> 104,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 72,
                'posY' => 898,
            ],
            [
                'number'=> 105,
                'floor'=> 2,
                'type'=>'left',
                'posX' => 72,
                'posY' => 870,
            ],
            [
                'number'=> 106,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 10,
                'posY' => 898,
            ],
            [
                'number'=> 107,
                'floor'=> 2,
                'type'=>'right',
                'posX' => 10,
                'posY' => 870,
            ],

        ];
        foreach ($places as $place) {
            $place = Place::create($place);
        }
    }
}
